version: 0.2

phases:
  install:
    commands:
      - npm install

  post_build:
    commands:
      - aws s3 sync . s3://tolerablebear.net --delete --exclude "*" --include "*.png" --include "*.js" --include "*.css" --include "*.html" --include "*.ico" --exclude "test*"
      - aws cloudfront create-invalidation --distribution-id E8P23T37L3H4M --paths "/*"
