version: 0.1

phases:
  install:
    commands:
      - echo "******** Installing NPM Projects ********"
      - npm install

  build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync . s3://tolerablebear.net --delete --exclude "*" --include "assets/*" --include "*.js" --include "*.css" --include "index.html" --exclude "test*"
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id EUTXATDDJG2N2 --paths /css* /assets* /libs* /app* /index.html
