name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'README.md'
    - '.gitignore'
    - 'LICENSE'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: npm ci
    - name: Copy Artifacts to S3
      run: aws s3 sync . s3://tolerablebear.net --delete --exclude "*" --include "*.png" --include "*.js" --include "*.css" --include "*.html" --include "*.ico" --exclude "test*"
    - name: Invalidate Cloudfront
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DIST_ID }} --paths "/*"
